### ISSUE TITLE
Error: 'ERR_HTTP_HEADERS_SENT'

### ISSUE THREAD

**Issue by andykov** [hawooni/hs-api-crypto-exchanges#1]
Hey. Thanks for the module.
I get a code error  **code: 'ERR_HTTP_HEADERS_SENT'** if you change the console.log to json

` router.get('/ticker', (req, res, next) => { `
      
    Exchange.bittrex.webSocket().ticker(['USD-BTC', 'USD-ETH'], (ticker) => {
      res.json(ticker)
    });
`});`

Do you know how to fix this?

**Comment by hawooni** [comment]
You should use tickers() not webSocket() for your code.
use tickers() then filter the symbols you want.
webSocket() is for live stream callback.

ERR_HTTP_HEADERS_SENT is due to header already sent to the client.
Here's the article you want to read.
https://www.codementor.io/@oparaprosper79/understanding-node-error-err_http_headers_sent-117mpk82z8

**Comment by andykov** [comment]
**return** at the end did not help.
How do I send data to a client?
I can listen to the desired websocket port on the client, but how do I know port?

**Comment by hawooni** [comment]
Express router.get() is for http get request. If you want to send live stream to your client you need to have web socket endpoints. Take a look at npm 'express-ws'.
https://www.npmjs.com/package/express-ws
